apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-webapp-ingress
  annotations:
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - host: java-webapp.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: java-webapp-service
                port:
                  number: 80
