apiVersion: networking.k8s.io/v1
kind: ingress
metadata:
  name: java-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - hosts: "yourfeatureworld.com"
      http:
        paths:
        - path: /java
          pathType: Prefix
          backend:
            service:
              name: java-app-service
              port: 8081